export interface LayoutPresetItem {
  id: string;
  label: string;
  desc: string;
  tag?: string;
}

export const SECTION_TYPE_LABELS: Record<string, string> = {
  header_announcement: 'Header & Bar Pengumuman',
  hero: 'Hero Section (Panggung Utama)',
  features: 'Fitur & Keunggulan Produk',
  product_catalog: 'Katalog Produk & Menu',
  testimonials: 'Testimoni & Ulasan Pelanggan',
  faq: 'Tanya Jawab (FAQ)',
  google_maps: 'Peta Lokasi & Kontak Toko',
  footer: 'Footer & Informasi Hak Cipta',
};

export const PRESETS_BY_SECTION_TYPE: Record<string, LayoutPresetItem[]> = {
  header_announcement: [
    { id: 'default_split', label: 'Split Default', desc: 'Bar pengumuman, logo kiri, nav tengah, tombol WA kanan', tag: 'Populer' },
    { id: 'centered_stacked', label: 'Centered Stacked', desc: 'Logo di atas tengah, deretan nav link rapi di bawah', tag: 'Simetris' },
    { id: 'compact_inline', label: 'Compact Inline', desc: 'Single-row ramping 56px tanpa bar pengumuman', tag: 'Minimalis' },
    { id: 'floating_pill_island', label: 'Floating Pill Island', desc: 'Navbar melayang berbentuk kapsul (rounded-full shadow-lg)', tag: 'Modern' },
    { id: 'split_nav_centered_logo', label: 'Split Nav Centered Logo', desc: 'Logo persis di tengah, nav terbagi rata di kiri dan kanan', tag: 'Editorial' },
    { id: 'command_search_bar', label: 'Command Search Bar', desc: 'Bar pencarian interaktif gaya ⌘K di tengah navbar', tag: 'E-Commerce' },
    { id: 'transparent_glass_header', label: 'Transparent Glass', desc: 'Latar transparan backdrop blur kaca di atas hero', tag: 'Glassmorphism' },
    { id: 'mega_menu_dropdown', label: 'Mega Menu Dropdown', desc: 'Nav link dengan panel dropdown kategori berikon', tag: 'Katalog Luas' },
    { id: 'top_contact_bar', label: 'Top Contact Bar', desc: 'Baris atas memuat jam & alamat, baris bawah menu utama', tag: 'F&B & Kuliner' },
    { id: 'delivery_order_cta', label: 'Delivery Order CTA', desc: 'Fokus pesan antar instan & status layanan kurir (GrabFood/GoFood)', tag: 'Resto' },
    { id: 'store_badge_highlight', label: 'Store Badge Highlight', desc: 'Sorotan legalitas toko (BPOM & Halal MUI) di samping logo', tag: 'Terpercaya' },
    { id: 'promo_countdown_banner', label: 'Promo Countdown Banner', desc: 'Baris atas memuat timer hitung mundur flash sale interaktif', tag: 'Promo' },
  ],
  hero: [
    { id: 'split_left_text', label: 'Split Teks Kiri', desc: 'Teks di kiri, media di kanan (50/50 split)', tag: 'Klasik' },
    { id: 'split_right_text', label: 'Split Teks Kanan', desc: 'Media di kiri, teks di kanan (50/50 split)', tag: 'Visual Utama' },
    { id: 'centered_minimal', label: 'Centered Minimal', desc: 'Judul tengah, CTA tengah, mockup visual 16:9 di bawah', tag: 'Populer' },
    { id: 'full_banner_overlay', label: 'Full Banner Overlay', desc: 'Gambar/video penuh dengan dark backdrop dan teks putih', tag: 'Sinematik' },
    { id: 'video_background_loop', label: 'Video Background Loop', desc: 'Looping ambient video latar dengan teks kontras tinggi', tag: 'Motion' },
    { id: 'gradient_mesh_glow', label: 'Gradient Mesh Glow', desc: 'Latar mesh netral halus dengan kartu CTA elegan', tag: 'Aesthetic' },
    { id: 'interactive_terminal_code', label: 'Interactive Terminal', desc: 'Teks judul berdampingan mockup terminal beranimasi', tag: 'Tech' },
    { id: 'floating_cards_showcase', label: 'Floating Cards Showcase', desc: 'Headline tengah dikelilingi kartu visual melayang berotasi halus', tag: 'Interaktif' },
    { id: 'oversized_bold_typography', label: 'Oversized Bold Typography', desc: 'Tipografi display raksasa dengan supporting card minimalis', tag: 'Editorial' },
    { id: 'inline_email_capture', label: 'Inline Email Capture', desc: 'Form input email/WA broadcast menyatu di bawah headline', tag: 'Lead Gen' },
    { id: 'social_proof_community', label: 'Social Proof Community', desc: 'Avatar wall pembeli, bintang rating 5/5, & jaminan mutu', tag: 'Konversi' },
    { id: 'dual_product_showcase', label: 'Dual Product Showcase', desc: 'Dua kartu varian produk terlaris dengan tombol pesan instan', tag: 'Retail' },
    { id: 'badge_ticker_split', label: 'Badge Ticker Split', desc: 'Hero split dengan baris badge sertifikasi halal/BPOM & stempel mutu', tag: 'Resmi' },
    { id: 'pill_category_selector', label: 'Pill Category Selector', desc: 'Hero terpusat dengan filter pill tag cepat kategori produk', tag: 'Katalog' },
    { id: 'bento_masonry_hero', label: 'Bento Grid Visual', desc: 'Layout ubin asimetris memuat teks promo, ulasan, foto, & info kirim', tag: 'Bento' },
    { id: 'split_stat_counter', label: 'Split Stat Counter', desc: 'Hero split 2 kolom dengan 3 baris metrik angka pencapaian penjualan', tag: 'Statistik' },
    { id: 'sticky_whatsapp_pill_float', label: 'Simulasi Chat WhatsApp', desc: 'Format dialog bubble chat otentik WhatsApp dengan tombol aksi', tag: 'WhatsApp' },
    { id: 'sticker_badge_playful', label: 'Sticker Badge Playful', desc: 'Badge stiker miring dinamis dengan visual berani & harga promo', tag: 'Playful' },
    { id: 'editorial_luxury_serif', label: 'Editorial Luxury Serif', desc: 'Tipografi serif elegan & tata letak editorial untuk kriya & fesyen', tag: 'Luxury' },
    { id: 'side_card_booking', label: 'Side Card Booking', desc: 'Form reservasi janji temu / meja mengambang di sisi samping', tag: 'Booking' },
    { id: 'dual_contrast_split', label: 'Dual Contrast Split', desc: 'Duo-tone kontras 50/50 sisi terang penawaran dan sisi gelap kuota', tag: 'Kontras' },
    { id: 'brand_story_founder', label: 'Kisah Pendiri / Artisan', desc: 'Narasi personal profil pendiri dengan kutipan filosofi dapur/toko', tag: 'Storytelling' },
  ],
  features: [
    { id: 'grid_3_cards', label: 'Grid 3 Kartu', desc: '3 Kolom kartu berbingkai rapi dengan icon container 48px', tag: 'Standar' },
    { id: 'horizontal_list', label: 'Horizontal List', desc: '2 Kolom asimetris: Judul sticky kiri, baris fitur kanan', tag: 'Ramping' },
    { id: 'banner_inline_bar', label: 'Banner Inline Ribbon', desc: 'Pita kontainer horizontal ramping 1 baris (64px)', tag: 'Kompak' },
    { id: 'bento_grid_asymmetric', label: 'Bento Grid Asimetris', desc: 'Bento grid dengan ubin beragam ukuran dan fitur sorotan', tag: 'Bento' },
    { id: 'alternating_zigzag_rows', label: 'Alternating Zigzag', desc: 'Baris bergantian kiri-kanan (teks-gambar & gambar-teks)', tag: 'Editorial' },
    { id: 'interactive_tabs', label: 'Interactive Tabs', desc: 'Tab pilihan yang mengganti preview fitur saat diklik', tag: 'Interaktif' },
    { id: 'vertical_accordion_showcase', label: 'Vertical Accordion', desc: 'Akordeon vertikal interaktif yang membuka detail fitur', tag: 'Collapsible' },
    { id: 'sticky_scroll_highlight', label: 'Sticky Scroll Highlight', desc: 'Visual kiri tetap sticky saat deskripsi fitur kanan di-scroll', tag: 'Sticky' },
    { id: 'dense_icon_matrix', label: 'Dense Icon Matrix', desc: 'Matriks ubin ikon kompak untuk menampilkan banyak benefit', tag: 'Matriks' },
    { id: 'before_after_comparison', label: 'Before & After Comparison', desc: 'Kartu komparasi visual Tanpa Sistem vs Dengan Sistem UMKM', tag: 'Komparasi' },
  ],
  product_catalog: [
    { id: 'grid_standard', label: 'Grid Standar Responsif', desc: 'Katalog grid 2/3/4 kolom rapi dengan quick view', tag: 'Klasik' },
    { id: 'carousel_scroll', label: 'Carousel Scroll', desc: 'Snap scroll horizontal untuk browsing geser cepat', tag: 'Carousel' },
    { id: 'list_compact', label: 'List Compact Rows', desc: 'Daftar baris produk ringkas cocok untuk menu makanan', tag: 'Menu Resto' },
    { id: 'masonry_catalog', label: 'Masonry Catalog', desc: 'Grid ketinggian bervariasi dengan badge promo', tag: 'Masonry' },
    { id: 'bento_product_spotlight', label: 'Bento Product Spotlight', desc: '1 Produk unggulan besar dikelilingi produk pendukung', tag: 'Spotlight' },
    { id: 'split_category_sidebar', label: 'Split Category Sidebar', desc: 'Sidebar filter kategori di kiri, daftar produk di kanan', tag: 'Filter' },
    { id: 'compact_mini_cards', label: 'Compact Mini Cards', desc: 'Kartu mini rapat efisien untuk katalog banyak item', tag: 'Efisien' },
    { id: 'price_table_view', label: 'Price Table View', desc: 'Tabel perbandingan harga & spesifikasi produk', tag: 'Tabel' },
    { id: 'lookbook_gallery', label: 'Lookbook Gallery', desc: 'Galeri editorial foto besar dengan pin tag harga popover', tag: 'Lookbook' },
    { id: 'flash_sale_countdown', label: 'Flash Sale Countdown', desc: 'Tema promo terbatas dengan banner timer mundur', tag: 'Flash Sale' },
  ],
  testimonials: [
    { id: 'masonry_grid', label: 'Masonry Grid 3 Kolom', desc: 'Grid 3 kolom kartu ulasan dengan bintang amber & verified badge', tag: 'Populer' },
    { id: 'single_spotlight', label: 'Single Spotlight Quote', desc: '1 Kutipan ulasan besar terpilih dengan pagination dot', tag: 'Editorial' },
    { id: 'chat_bubble_flow', label: 'Chat Bubble Flow', desc: 'Gelembung obrolan WhatsApp autentik dengan label hijau', tag: 'WhatsApp' },
    { id: 'infinite_marquee_scroll', label: 'Infinite Marquee Ticker', desc: 'Deretan kartu ulasan yang bergeser horizontal otomatis', tag: 'Marquee' },
    { id: 'video_review_cards', label: 'Video Review Cards', desc: 'Grid thumbnail video pelanggan dengan tombol play', tag: 'Video' },
    { id: 'social_post_cards', label: 'Social Post Feed', desc: 'Format postingan media sosial dengan avatar, handle, & like', tag: 'Sosmed' },
    { id: 'side_by_side_3_cards', label: 'Side-by-Side 3 Cards', desc: '3 Kartu sejajar dengan foto pelanggan besar & rating tebal', tag: 'Minimalis' },
    { id: 'logo_client_cloud', label: 'Logo Client Cloud', desc: 'Deretan logo mitra/klien UMKM bersih dengan judul pengantar', tag: 'Mitra' },
    { id: 'split_rating_stats', label: 'Split Rating Stats', desc: 'Skor agregat bintang 4.9/5 di kiri, daftar ulasan di kanan', tag: 'Statistik' },
    { id: 'carousel_slider', label: 'Carousel Slider Nav', desc: 'Slider interaktif dengan tombol navigasi panah kiri-kanan', tag: 'Slider' },
  ],
  faq: [
    { id: 'accordion_single_col', label: 'Accordion Single Column', desc: 'Akordeon terpusat 1 kolom dengan rotasi chevron halus', tag: 'Klasik' },
    { id: 'split_faq_sidebar', label: 'Split FAQ Sidebar', desc: 'Judul & kartu bantuan CS WhatsApp di kiri, akordeon di kanan', tag: 'Split' },
    { id: 'grid_2_col_cards', label: 'Grid 2 Kolom Terbuka', desc: 'Grid 2 kolom kartu tanya-jawab terbuka permanen', tag: 'Terbuka' },
    { id: 'accordion_two_col', label: 'Accordion Two Column', desc: 'Akordeon yang terbagi seimbang ke dalam 2 kolom sejajar', tag: '2 Kolom' },
    { id: 'chat_style_faq', label: 'Chat Style Bubble FAQ', desc: 'Tanya jawab bergaya balon percakapan pesan interaktif', tag: 'Chat' },
    { id: 'search_filtered_faq', label: 'Search Filtered FAQ', desc: 'Kolom pencarian yang memfilter pertanyaan secara instan', tag: 'Cari' },
    { id: 'categorized_tabs_faq', label: 'Categorized Tabs FAQ', desc: 'Tab kategori di atas untuk memilah topik pertanyaan', tag: 'Tabs' },
    { id: 'compact_numbered_list', label: 'Compact Numbered List', desc: 'Daftar bernomor urut minimalis (01, 02, 03) collapsible', tag: 'Nomor' },
    { id: 'floating_help_center', label: 'Floating Help Center', desc: 'Kartu FAQ terintegrasi link chat CS WhatsApp langsung', tag: 'Helpdesk' },
    { id: 'horizontal_faq_cards', label: 'Horizontal FAQ Cards', desc: 'Kartu tanya jawab horizontal geser yang ringkas', tag: 'Horizontal' },
  ],
  google_maps: [
    { id: 'fullwidth_map', label: 'Fullwidth Floating Card', desc: 'Peta penuh dengan floating address card di sudut', tag: 'Fullwidth' },
    { id: 'split_map_info', label: 'Split Map Info', desc: 'Alamat, jam operasional, & tombol rute di kiri, peta di kanan', tag: 'Split' },
    { id: 'compact_boxed', label: 'Compact Boxed Card', desc: 'Kartu ringkas terpusat dengan preview iframe peta', tag: 'Boxed' },
    { id: 'floating_address_card', label: 'Floating Address Card', desc: 'Peta terpusat dengan kartu alamat mengambang di atas', tag: 'Floating' },
    { id: 'two_column_directions', label: 'Two Column Directions', desc: 'Panduan rute & transportasi di kiri, peta di kanan', tag: 'Panduan' },
    { id: 'store_hours_highlight', label: 'Store Hours Highlight', desc: 'Banner jam kerja operasional mencolok di samping peta', tag: 'Jam Buka' },
    { id: 'interactive_route_finder', label: 'Interactive Route Finder', desc: 'Tombol pintas petunjuk arah dengan perkiraan jarak', tag: 'Rute' },
    { id: 'minimal_framed_map', label: 'Minimal Framed Map', desc: 'Bingkai peta elegan bergaris tepi tipis dengan caption', tag: 'Minimalis' },
    { id: 'multi_branch_tabs', label: 'Multi Branch Tabs', desc: 'Tab pemilih cabang toko untuk berganti lokasi peta', tag: 'Cabang' },
    { id: 'card_overlay_bottom', label: 'Card Overlay Bottom', desc: 'Bar info kaca transparan di bagian bawah frame peta', tag: 'Overlay' },
  ],
  footer: [
    { id: 'multi_column', label: 'Multi Column Standard', desc: '3-4 Kolom (Profil Toko, Kontak WA, Menu, Hak Cipta)', tag: 'Klasik' },
    { id: 'centered_simple', label: 'Centered Simple', desc: 'Layout minimalis terpusat dengan tombol WA bulat', tag: 'Simple' },
    { id: 'cta_focused', label: 'CTA Focused Banner', desc: 'Banner WhatsApp floating card menonjol di atas info footer', tag: 'CTA WA' },
    { id: 'minimal_single_row', label: 'Minimal Single Row', desc: '1 Baris ramping: logo di kiri, link tengah, copyright kanan', tag: '1 Baris' },
    { id: 'giant_wordmark', label: 'Giant Wordmark Display', desc: 'Nama brand berukuran raksasa sebagai visual utama', tag: 'Branding' },
    { id: 'newsletter_centric', label: 'Newsletter & WA Broadcast', desc: 'Form langganan broadcast WhatsApp di bagian atas footer', tag: 'Broadcast' },
    { id: 'live_status_badge', label: 'Live Store Status', desc: 'Indikator status operasional toko live buka hari ini', tag: 'Status Buka' },
    { id: 'split_map_footer', label: 'Split Map Footer', desc: 'Integrasi thumbnail peta lokasi toko di sisi kanan footer', tag: 'Peta' },
    { id: 'social_links_grid', label: 'Social & Marketplace Grid', desc: 'Grid tautan resmi media sosial dan marketplace toko UMKM', tag: 'Sosmed' },
    { id: 'boxed_card_footer', label: 'Boxed Card Container', desc: 'Footer berbingkai kartu terpisah dari tepi dasar layar', tag: 'Boxed' },
  ],
};
