/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-dark': 'var(--color-primary-dark)',
        secondary: 'var(--color-secondary)',
        success: 'var(--color-success)',
        error: 'var(--color-error)',
        warning: 'var(--color-warning)',
        text: 'var(--color-text)',
        'text-muted': 'var(--color-text-muted)',
        bg: 'var(--color-bg)',
        'bg-muted': 'var(--color-bg-muted)',
        border: 'var(--color-border)',
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
      },
      fontFamily: {
        sans: 'var(--font-family-sans)',
        mono: 'var(--font-family-mono)',
      },
      fontSize: {
        sm: 'var(--font-size-sm)',
        base: 'var(--font-size-base)',
        lg: 'var(--font-size-lg)',
        xl: 'var(--font-size-xl)',
      },
      lineHeight: {
        tight: 'var(--line-height-tight)',
        normal: 'var(--line-height-normal)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      transitionDuration: {
        fast: 'var(--transition-fast)',
        base: 'var(--transition-base)',
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        light: {
          primary: '#4f46e5',
          'primary-content': '#ffffff',
          secondary: '#7c3aed',
          accent: '#06b6d4',
          neutral: '#3f3f46',
          'base-100': '#ffffff',
          'base-200': '#f8f9ff',
          'base-300': '#eff4ff',
          'base-content': '#0b1c30',
          success: '#10b981',
          error: '#ef4444',
          warning: '#f59e0b',
          info: '#3b82f6',
        },
        dark: {
          primary: '#4f46e5',
          'primary-content': '#ffffff',
          secondary: '#7c3aed',
          accent: '#06b6d4',
          neutral: '#e4e4e7',
          'base-100': '#161e31',
          'base-200': '#0a0f1e',
          'base-300': '#1c263c',
          'base-content': '#f8f9ff',
          success: '#10b981',
          error: '#ef4444',
          warning: '#f59e0b',
          info: '#3b82f6',
        },
      },
    ],
    base: true,
    styled: true,
    utils: true,
  },
};
