import type { ComponentType } from 'svelte';
import {
  MapPin,
  Navigation,
  Compass,
  Clock,
  Flag,
  Car,
  Building2,
  ExternalLink,
  ShieldCheck,
  MessageCircle,
  Sparkles,
  Store,
  Phone,
  ArrowRight,
  Search,
  CheckCircle,
  Map,
  Award,
  Star,
  Users,
  Info,
} from 'lucide-svelte';

export const MAPS_ICON_MAP: Record<string, ComponentType> = {
  'map-pin': MapPin,
  MapPin,
  navigation: Navigation,
  Navigation,
  compass: Compass,
  Compass,
  clock: Clock,
  Clock,
  flag: Flag,
  Flag,
  car: Car,
  Car,
  building: Building2,
  'building-2': Building2,
  Building2,
  'external-link': ExternalLink,
  ExternalLink,
  'shield-check': ShieldCheck,
  ShieldCheck,
  'message-circle': MessageCircle,
  MessageCircle,
  sparkles: Sparkles,
  Sparkles,
  store: Store,
  Store,
  phone: Phone,
  Phone,
  'arrow-right': ArrowRight,
  ArrowRight,
  search: Search,
  Search,
  'check-circle': CheckCircle,
  CheckCircle,
  map: Map,
  Map,
  award: Award,
  Award,
  star: Star,
  Star,
  users: Users,
  Users,
  info: Info,
  Info,
};

export function resolveMapIcon(name?: string): ComponentType {
  if (!name) return MapPin as unknown as ComponentType;
  const normalized = name.trim().toLowerCase().replace(/[_\s]+/g, '-');
  return (MAPS_ICON_MAP[name] || MAPS_ICON_MAP[normalized] || MapPin) as unknown as ComponentType;
}

export const MAP_ICON_OPTIONS = [
  { value: 'map-pin', label: 'MapPin / Lokasi Toko' },
  { value: 'building-2', label: 'Building2 / Gerai & Kantor' },
  { value: 'store', label: 'Store / Toko Fisik' },
  { value: 'sparkles', label: 'Sparkles / Unggulan' },
  { value: 'award', label: 'Award / Resmi Terpercaya' },
  { value: 'star', label: 'Star / Bintang Terverifikasi' },
  { value: 'clock', label: 'Clock / Jam Buka' },
  { value: 'shield-check', label: 'ShieldCheck / Legal & Aman' },
  { value: 'navigation', label: 'Navigation / Petunjuk Arah' },
  { value: 'compass', label: 'Compass / Penunjuk Rute' },
  { value: 'car', label: 'Car / Akses Parkir' },
  { value: 'flag', label: 'Flag / Patokan Lokasi' },
  { value: 'message-circle', label: 'MessageCircle / Kontak WA' },
];

export const MAP_CTA_ICON_OPTIONS = [
  { value: 'navigation', label: 'Navigation / Navigasi Arah' },
  { value: 'compass', label: 'Compass / Panduan Rute' },
  { value: 'external-link', label: 'ExternalLink / Buka Maps' },
  { value: 'map-pin', label: 'MapPin / Titik Lokasi' },
  { value: 'arrow-right', label: 'ArrowRight / Panah Kanan' },
  { value: 'building-2', label: 'Building2 / Kunjungi Cabang' },
  { value: 'message-circle', label: 'MessageCircle / Hubungi WA' },
];
