import type { ComponentType } from 'svelte';
import {
  Sparkles,
  ShieldCheck,
  Shield,
  Truck,
  Wheat,
  Users,
  Leaf,
  Zap,
  Package,
  CreditCard,
  Award,
  Check,
  X,
  Star,
  Clock,
  Heart,
  Coffee,
  BadgeCheck,
  BadgePercent,
  Layers,
  MessageCircle,
  MapPin,
  Phone,
  Gem,
  Flame,
  Tag,
  ThumbsUp,
  Smile,
  ShoppingBag,
  DollarSign,
  CheckCircle2,
  Headphones,
  CheckCircle,
  TrendingUp,
  Gift,
  Box,
  Scale,
  Sun,
  Lock,
  RefreshCw,
  Percent,
} from 'lucide-svelte';

export const FEATURE_ICON_MAP: Record<string, ComponentType> = {
  // Common names & aliases
  shield: ShieldCheck,
  'shield-check': ShieldCheck,
  ShieldCheck: ShieldCheck,
  Shield: Shield,
  truck: Truck,
  Truck: Truck,
  award: Award,
  Award: Award,
  star: Star,
  Star: Star,
  zap: Zap,
  Zap: Zap,
  sparkles: Sparkles,
  Sparkles: Sparkles,
  wheat: Wheat,
  Wheat: Wheat,
  handshake: Users,
  Handshake: Users,
  users: Users,
  Users: Users,
  leaf: Leaf,
  Leaf: Leaf,
  package: Package,
  Package: Package,
  'credit-card': CreditCard,
  CreditCard: CreditCard,
  clock: Clock,
  Clock: Clock,
  heart: Heart,
  Heart: Heart,
  coffee: Coffee,
  Coffee: Coffee,
  'badge-check': BadgeCheck,
  BadgeCheck: BadgeCheck,
  'badge-percent': BadgePercent,
  BadgePercent: BadgePercent,
  layers: Layers,
  Layers: Layers,
  'message-circle': MessageCircle,
  MessageCircle: MessageCircle,
  'map-pin': MapPin,
  MapPin: MapPin,
  phone: Phone,
  Phone: Phone,
  gem: Gem,
  Gem: Gem,
  flame: Flame,
  Flame: Flame,
  tag: Tag,
  Tag: Tag,
  'thumbs-up': ThumbsUp,
  ThumbsUp: ThumbsUp,
  smile: Smile,
  Smile: Smile,
  'shopping-bag': ShoppingBag,
  ShoppingBag: ShoppingBag,
  'dollar-sign': DollarSign,
  DollarSign: DollarSign,
  check: Check,
  Check: Check,
  'check-circle': CheckCircle,
  CheckCircle: CheckCircle,
  'check-circle-2': CheckCircle2,
  CheckCircle2: CheckCircle2,
  x: X,
  X: X,
  headphones: Headphones,
  Headphones: Headphones,
  'trending-up': TrendingUp,
  TrendingUp: TrendingUp,
  gift: Gift,
  Gift: Gift,
  box: Box,
  Box: Box,
  scale: Scale,
  Scale: Scale,
  sun: Sun,
  Sun: Sun,
  lock: Lock,
  Lock: Lock,
  'refresh-cw': RefreshCw,
  RefreshCw: RefreshCw,
  percent: Percent,
  Percent: Percent,
};

export function resolveFeatureIcon(name?: string): ComponentType {
  if (!name) return Sparkles as unknown as ComponentType;
  const normalized = name.trim().toLowerCase().replace(/[_\s]+/g, '-');
  return (FEATURE_ICON_MAP[name] || FEATURE_ICON_MAP[normalized] || Sparkles) as unknown as ComponentType;
}

export const FEATURE_ICON_OPTIONS = [
  { value: 'shield-check', label: 'Shield / Keamanan' },
  { value: 'truck', label: 'Truck / Pengiriman' },
  { value: 'award', label: 'Award / Kualitas' },
  { value: 'sparkles', label: 'Sparkles / Unggulan' },
  { value: 'wheat', label: 'Wheat / Alami Organik' },
  { value: 'users', label: 'Users / Kemitraan Petani' },
  { value: 'leaf', label: 'Leaf / Herbal Ramah Lingkungan' },
  { value: 'zap', label: 'Zap / Cepat Responsif' },
  { value: 'package', label: 'Package / Kemasan' },
  { value: 'credit-card', label: 'CreditCard / Pembayaran COD' },
  { value: 'clock', label: 'Clock / 24 Jam' },
  { value: 'heart', label: 'Heart / Favorit' },
  { value: 'coffee', label: 'Coffee / Kuliner Rasa' },
  { value: 'badge-check', label: 'BadgeCheck / Terverifikasi BPOM' },
  { value: 'badge-percent', label: 'BadgePercent / Promo Diskon' },
  { value: 'star', label: 'Star / Rating Bintang' },
  { value: 'thumbs-up', label: 'ThumbsUp / Rekomendasi' },
  { value: 'gem', label: 'Gem / Mewah Premium' },
  { value: 'flame', label: 'Flame / Terlaris Hot' },
  { value: 'message-circle', label: 'MessageCircle / Chat WhatsApp' },
  { value: 'gift', label: 'Gift / Bonus Hadiah' },
  { value: 'refresh-cw', label: 'RefreshCw / Garansi Retur' },
];
